# Generated by Django 5.1.4 on 2025-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_teachers'),
        ('teachers', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_subjects', to='teachers.teacher'),
        ),
    ]
